# Generated by Django 4.2.3 on 2023-07-10 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0002_alter_category_options_items'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='items',
            options={'ordering': ('name',), 'verbose_name_plural': 'Items'},
        ),
        migrations.AddField(
            model_name='items',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='items_images'),
        ),
    ]
